// .vitepress/theme/components/PubBadge.vue
<script setup lang="ts">
const props = defineProps<{
  package: string;
}>();
</script>

<template>
  <a
    :href="`https://pub.dev/packages/${props.package}`"
    target="_blank"
    rel="noopener noreferrer"
    class="pub-badge"
  >
    <img
      :src="`https://img.shields.io/pub/v/${props.package}.svg`"
      :alt="`${props.package} on pub.dev`"
      loading="lazy"
    />
  </a>
</template>

<style scoped>
@reference "../style.css";

.pub-badge {
  @apply inline-flex items-center no-underline;
}

.pub-badge img {
  @apply h-5;
}
</style>

// src/components/PubBadge.tsx
import type { Props } from 'astro'
import type { FunctionComponent } from 'react'

export const PubBadge: FunctionComponent<Props> = (props) => {
  const { name, inline } = props

  return (
    <a
      href={`https://pub.dev/packages/${name}`}
      className={inline ? 'inline-block px-1' : 'block pb-4'}
    >
      <img
        alt="pub"
        src={`https://img.shields.io/pub/v/${name}.svg?label=${name}&logo=dart&color=blue&style=for-the-badge`}
      />
    </a>
  )
}
